### ISSUE TITLE
EOF Error when using pip install dash-bootstrap-components python 3.6

### ISSUE THREAD

**Issue by avivazran** [facultyai/dash-bootstrap-components#390]
running pip install the package throws the following
```
  Installing build dependencies ... error
  ERROR: Command errored out with exit status 2:
   command: 'c:\python36\python.exe' 'c:\python36\lib\site-packages\pip' install --ignore-installed --no-user --prefix 'C:\Users\mvhlab\AppData\Local\Temp\pip-build-env-59f_7kfj\overlay' --no-warn-script-location --no-binary :none: --only-binary :none: -i https://intelpypi.pdx.intel.com/pythonsv/staging -- 'setuptools >= 40.8.0' wheel
       cwd: None
  Complete output (49 lines):
  Keyring is skipped due to an exception: 'WindowsPath' object has no attribute 'read_text'
  Looking in indexes: https://intelpypi.pdx.intel.com/pythonsv/staging
  User for intelpypi.pdx.intel.com: ERROR: Exception:
  Traceback (most recent call last):
    File "c:\python36\lib\site-packages\pip\_internal\cli\base_command.py", line 188, in _main
      status = self.run(options, args)
    File "c:\python36\lib\site-packages\pip\_internal\cli\req_command.py", line 185, in wrapper
      return func(self, options, args)
    File "c:\python36\lib\site-packages\pip\_internal\commands\install.py", line 333, in run
      reqs, check_supported_wheels=not options.target_dir
    File "c:\python36\lib\site-packages\pip\_internal\resolution\legacy\resolver.py", line 179, in resolve
      discovered_reqs.extend(self._resolve_one(requirement_set, req))
    File "c:\python36\lib\site-packages\pip\_internal\resolution\legacy\resolver.py", line 362, in _resolve_one
      abstract_dist = self._get_abstract_dist_for(req_to_install)
    File "c:\python36\lib\site-packages\pip\_internal\resolution\legacy\resolver.py", line 313, in _get_abstract_dist_for
      self._populate_link(req)
    File "c:\python36\lib\site-packages\pip\_internal\resolution\legacy\resolver.py", line 279, in _populate_link
      req.link = self.finder.find_requirement(req, upgrade)
    File "c:\python36\lib\site-packages\pip\_internal\index\package_finder.py", line 901, in find_requirement
      req.name, specifier=req.specifier, hashes=hashes,
    File "c:\python36\lib\site-packages\pip\_internal\index\package_finder.py", line 883, in find_best_candidate
      candidates = self.find_all_candidates(project_name)
    File "c:\python36\lib\site-packages\pip\_internal\index\package_finder.py", line 828, in find_all_candidates
      project_url, link_evaluator=link_evaluator,
    File "c:\python36\lib\site-packages\pip\_internal\index\package_finder.py", line 792, in process_project_url
      html_page = self._link_collector.fetch_page(project_url)
    File "c:\python36\lib\site-packages\pip\_internal\index\collector.py", line 612, in fetch_page
      return _get_html_page(location, session=self.session)
    File "c:\python36\lib\site-packages\pip\_internal\index\collector.py", line 451, in _get_html_page
      resp = _get_html_response(url, session=session)
    File "c:\python36\lib\site-packages\pip\_internal\index\collector.py", line 166, in _get_html_response
      "Cache-Control": "max-age=0",
    File "c:\python36\lib\site-packages\pip\_vendor\requests\sessions.py", line 543, in get
      return self.request('GET', url, **kwargs)
    File "c:\python36\lib\site-packages\pip\_internal\network\session.py", line 421, in request
      return super(PipSession, self).request(method, url, *args, **kwargs)
    File "c:\python36\lib\site-packages\pip\_vendor\requests\sessions.py", line 530, in request
      resp = self.send(prep, **send_kwargs)
    File "c:\python36\lib\site-packages\pip\_vendor\requests\sessions.py", line 650, in send
      r = dispatch_hook('response', hooks, r, **kwargs)
    File "c:\python36\lib\site-packages\pip\_vendor\requests\hooks.py", line 31, in dispatch_hook
      _hook_data = hook(hook_data, **kwargs)
    File "c:\python36\lib\site-packages\pip\_internal\network\auth.py", line 246, in handle_401
      username, password, save = self._prompt_for_password(parsed.netloc)
    File "c:\python36\lib\site-packages\pip\_internal\network\auth.py", line 218, in _prompt_for_password
      username = ask_input("User for {}: ".format(netloc))
    File "c:\python36\lib\site-packages\pip\_internal\utils\misc.py", line 256, in ask_input
      return input(message)
  EOFError: EOF when reading a line
  ----------------------------------------
ERROR: Command errored out with exit status 2: 'c:\python36\python.exe' 'c:\python36\lib\site-packages\pip' install --ignore-installed --no-user --prefix 'C:\Users\mvhlab\AppData\Local\Temp\pip-build-env-59f_7kfj\overlay' --no-warn-script-location --no-binary :none: --only-binary :none: -i https://intelpypi.pdx.intel.com/pythonsv/staging -- 'setuptools >= 40.8.0' wheel Check the logs for full command output.
```
can you please provide a solution?

**Comment by tcbegley** [comment]
It looks like the issue is that you're searching in a private package index and then pip is failing to retrieve username and password?

```
Looking in indexes: https://intelpypi.pdx.intel.com/pythonsv/staging
...
File "c:\python36\lib\site-packages\pip\_internal\network\auth.py", line 246, in handle_401
  username, password, save = self._prompt_for_password(parsed.netloc)
File "c:\python36\lib\site-packages\pip\_internal\network\auth.py", line 218, in _prompt_for_password
  username = ask_input("User for {}: ".format(netloc))
File "c:\python36\lib\site-packages\pip\_internal\utils\misc.py", line 256, in ask_input
  return input(message)
EOFError: EOF when reading a line
```

I don't know exactly what your setup is, but probably worth taking a look in your `pip.conf` file to figure out where `pip` is searching for packages, and whether it's possible to point it at PyPI to install dash-bootstrap-components. It would also be good to understand how you normally authenticate access to this private index and why it wasn't working in this case.

You can specify indexes when installing like this

```
pip install --index-url https://pypi.org/simple dash-bootstrap-components
```

which might help, but if `pip` still tries to access your private index it's quite possible that the authentication issue leads to the same problem.

**Comment by tcbegley** [comment]
As a follow-up, since it seems `pip` is failing while asking for user input

```
File "c:\python36\lib\site-packages\pip\_internal\utils\misc.py", line 256, in ask_input
    return input(message)
```

perhaps you could try installing with the `--no-input` flag?

**Comment by tcbegley** [comment]
Closing due to no response, please reopen if you're still having issues.

**Comment by avivazran** [comment]
I'm trying to install the package on my company laptop. it does have a private PyPi index.
when I install a package, I'm required to insert user name and password but it is configured now for using my stored credentials and i'm installing other packages without problems.
Two things I've noticed:

1. if I download the tar.gz file and run `python setup.py install` - it installs without problem (yet, this is against company policy so it's a workaround i can't actually use)

2. All the other dash-related packages installers work fine.

As i mentioned in the header, python 3.6 is installed. is it related? is there anything that can be done?

**Comment by tcbegley** [comment]
What packages are hosted on the company index? Is it possible that the other Dash packages are listed there and that PyPI itself is not accessible due to a firewall? That would at least explain why one installs but not the other. I don't _think_ it's going to be related to Python 3.6 specifically?

**Comment by avivazran** [comment]
dash-bootstrap-components is also listed there
